### ISSUE TITLE
"Teacher Model" was not found 

### ISSUE THREAD

**Issue by Dan-Jia** [Frostinassiky/mlod.tf#2]
In **./lib/datasets/pascal_voc.py** I saw pseudo boxes were loaded through the function "_load_annotation",  and there should be a file with this path:

`  image_gt_file = os.path.join(self.cache_path, '..', 'pseudo', 'voc_' + self._year + '_' + self._image_set + '_gt.mat')`

But I didn't find this MatLab file, namely, I didn't find where generating pseudo data was achieved (in the paper " Missing Labels in Object Detection" this part should be "Teacher Model" and "W2F" model is used.)

Does anybody know where it is or it was still not in this repository yet?

**Comment by frostinassiky** [comment]
Hello @shellswestern  

In this work, we 'learn' the teacher model from its prediction. I have uploaded the pseudo boxes files to Amazon S3. 

``` 
cd data/pseudo
wget https://reserach-project.s3.eu-west-2.amazonaws.com/mlod/W2F.mat 
cp W2F.mat voc_2007_trainval_gt.mat
```

After that, please refer the batch file `test_train.batch` to see the way to update the pseudo labels.

**Comment by Dan-Jia** [comment]
Thx for your reply :)
