### ISSUE TITLE
How to use this code on my own data?

### ISSUE THREAD

**Issue by HanshengLee** [Frostinassiky/mlod.tf#3]
It is a amazing work, and I'm interested in your excellent work. Can you tell me how to train the network on my VOC like dataset (annotations in xml format)?

**Comment by frostinassiky** [comment]
Hey Hansheng, thanks for your interest in the work.
Please find the this [repo](https://github.com/Frostinassiky/Bi-Level-Converter) to generate the VOC-liked dataset. We save everything in json format.
